name: visible_on_focus
description: "a Flutter widget that automatically scrolls a focused text field (or any other focusable widget) into view when the keyboard appears"
version: 0.0.1
homepage: https://github.com/IshuPrabhakar/VisibleOnFocus.git
repository: https://github.com/IshuPrabhakar/VisibleOnFocus.git

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
